# Generated by Django 3.2.25 on 2024-07-24 00:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=256)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=16)),
                ('address', models.CharField(blank=True, db_index=True, max_length=2056)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
