fail_fast: true
default_language_version:
    python: python3.8
repos:
    - repo: https://github.com/python/black
      rev: 22.3.0
      hooks:
          - id: black
            language_version: python3.8
            args: ["--config", "pyproject.toml"]
    - repo: https://github.com/pycqa/flake8
      rev: 3.8.4
      hooks:
          - id: flake8
            name: flake8
            args: ["--config=setup.cfg"]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
          - id: trailing-whitespace
            name: check for trailing spaces
          - id: check-added-large-files
            name: check for large files
            args: ["--maxkb=1024"]
          - id: check-ast
            name: check python syntax
            types: [python]
          #    -   id: check-json
          #        name: check json
          #        types: [json]
          - id: debug-statements
            name: check for debug statements
            types: [python]
          #    -   id: detect-private-key
          #        name: check for private data
          - id: mixed-line-ending
            name: check line endings
            args: ["--fix=lf"]
            types: [python]
    #    -   id: pretty-format-json
    #        name: check pretty json
    - repo: https://github.com/asottile/blacken-docs
      rev: v1.12.1
      hooks:
          - id: blacken-docs
    # -   repo: https://github.com/asottile/pyupgrade
    #     rev: v1.21.0
    #     hooks:
    #     -   id: pyupgrade
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
            name: isort